# Generated by Django 4.2.16 on 2025-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics/"
            ),
        ),
    ]
