# Generated by Django 4.2.16 on 2025-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Register", "0002_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
