# Generated by Django 4.2.16 on 2025-02-06 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="participants",
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="room",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="text",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(default="message"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ChatAttachment",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
