# Generated by Django 4.2.16 on 2025-02-09 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="read",
            new_name="is_read",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="content",
            new_name="message",
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="file",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="room",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="participant1",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="participant2",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="updated_at",
        ),
    ]
