# Generated by Django 4.2.16 on 2025-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatroom_chatmessage_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
