# Generated by Django 4.2.16 on 2025-02-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_chatmessage_is_typing_chatmessage_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_typing",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="room",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="seen",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
