# Generated by Django 4.2.16 on 2025-02-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_item_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemImage",
        ),
    ]
