# Generated by Django 4.2.16 on 2025-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
