# Generated by Django 4.2.16 on 2025-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0004_order_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="completed",
                max_length=10,
            ),
        ),
    ]
