# Generated by Django 5.1.7 on 2025-03-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Career",
        ),
        migrations.DeleteModel(
            name="Update",
        ),
    ]
