# Generated by Django 5.1.7 on 2025-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0002_delete_career_delete_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="About MeroVada", max_length=200),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Your trusted partner in connecting owners and renters for a seamless, sustainable rental experience across Nepal and beyond."
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=200),
                ),
                (
                    "mission_description",
                    models.TextField(
                        default="MeroVada is dedicated to empowering individuals and businesses by offering a reliable, user-friendly platform for renting and sharing resources."
                    ),
                ),
                (
                    "vision_title",
                    models.CharField(default="Our Vision", max_length=200),
                ),
                (
                    "vision_description",
                    models.TextField(
                        default="We aspire to lead the global shift toward a sharing economy, where resources are maximized, waste is minimized, and communities thrive."
                    ),
                ),
                ("story_title", models.CharField(default="Our Story", max_length=200)),
                (
                    "story_description",
                    models.TextField(
                        default="Established in 2023, MeroVada was born from a vision to revolutionize how people access and share resources."
                    ),
                ),
                (
                    "story_image",
                    models.ImageField(blank=True, null=True, upload_to="about_us/"),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
    ]
