# Generated by Django 5.1.7 on 2025-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_contactsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class, e.g., 'fas fa-hand-holding-usd'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefit",
                "verbose_name_plural": "Benefits",
            },
        ),
        migrations.CreateModel(
            name="CompanyCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class, e.g., 'fas fa-lightbulb'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Culture",
                "verbose_name_plural": "Company Culture",
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Remote", "Remote"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
    ]
