# Generated by Django 5.1.7 on 2025-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_benefit_companyculture_jobposting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefit",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="companyculture",
            name="icon_class",
        ),
        migrations.AddField(
            model_name="benefit",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this benefit",
                null=True,
                upload_to="benefit_images/",
            ),
        ),
        migrations.AddField(
            model_name="companyculture",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this culture item",
                null=True,
                upload_to="culture_images/",
            ),
        ),
    ]
